version: '3'

services:

  temperature-microservice:
    image: temperature-microservice-df:0.0.1-SNAPSHOT
    ports:
      - "8881:8881"
    
  humidity-microservice:
    image: humidity-microservice-df:0.0.1-SNAPSHOT
    ports:
      - "8882:8882"
    
  aggregator-microservice:
    image: aggregator-microservice-df:0.0.1-SNAPSHOT
    ports:
      - "8883:8883"
    depends_on:
      - temperature-microservice
      - humidity-microservice